//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTwister.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoTwister.Resources.Localization.Common.en-US", typeof(Common_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left foot on air.
        /// </summary>
        internal static string LeftFootAir {
            get {
                return ResourceManager.GetString("LeftFootAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left foot on blue.
        /// </summary>
        internal static string LeftFootBlue {
            get {
                return ResourceManager.GetString("LeftFootBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left foot on green.
        /// </summary>
        internal static string LeftFootGreen {
            get {
                return ResourceManager.GetString("LeftFootGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left foot on red.
        /// </summary>
        internal static string LeftFootRed {
            get {
                return ResourceManager.GetString("LeftFootRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left foot on yellow.
        /// </summary>
        internal static string LeftFootYellow {
            get {
                return ResourceManager.GetString("LeftFootYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left hand on air.
        /// </summary>
        internal static string LeftHandAir {
            get {
                return ResourceManager.GetString("LeftHandAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left hand on blue.
        /// </summary>
        internal static string LeftHandBlue {
            get {
                return ResourceManager.GetString("LeftHandBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left hand on green.
        /// </summary>
        internal static string LeftHandGreen {
            get {
                return ResourceManager.GetString("LeftHandGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left hand on red.
        /// </summary>
        internal static string LeftHandRed {
            get {
                return ResourceManager.GetString("LeftHandRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left hand on yellow.
        /// </summary>
        internal static string LeftHandYellow {
            get {
                return ResourceManager.GetString("LeftHandYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right foot on air.
        /// </summary>
        internal static string RightFootAir {
            get {
                return ResourceManager.GetString("RightFootAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right foot on blue.
        /// </summary>
        internal static string RightFootBlue {
            get {
                return ResourceManager.GetString("RightFootBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right foot on green.
        /// </summary>
        internal static string RightFootGreen {
            get {
                return ResourceManager.GetString("RightFootGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right foot on red.
        /// </summary>
        internal static string RightFootRed {
            get {
                return ResourceManager.GetString("RightFootRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right foot on yellow.
        /// </summary>
        internal static string RightFootYellow {
            get {
                return ResourceManager.GetString("RightFootYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right hand on air.
        /// </summary>
        internal static string RightHandAir {
            get {
                return ResourceManager.GetString("RightHandAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right hand on blue.
        /// </summary>
        internal static string RightHandBlue {
            get {
                return ResourceManager.GetString("RightHandBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right hand on green.
        /// </summary>
        internal static string RightHandGreen {
            get {
                return ResourceManager.GetString("RightHandGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right hand on red.
        /// </summary>
        internal static string RightHandRed {
            get {
                return ResourceManager.GetString("RightHandRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right hand on yellow.
        /// </summary>
        internal static string RightHandYellow {
            get {
                return ResourceManager.GetString("RightHandYellow", resourceCulture);
            }
        }
    }
}
